[theme]
primaryColor = "#1976D2"                # Deep blue for accents/buttons
backgroundColor = "#FAFAFA"              # Very light gray for main background
secondaryBackgroundColor = "#E3F2FD"     # Soft blue for cards/sidebars
textColor = "#212121"                    # Dark gray for text
font = "sans serif"
